version: '3.8'
 
services:
 
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=productsDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
     
  dbadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - dbadmin:/root/.pgadmin

  cache:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
 
volumes:
  db_data:
  dbadmin:
  cache_data: